### ISSUE TITLE
Blob type file don't have name attribute?

### ISSUE THREAD

**Issue by Kalipts** [onurzorluer/react-image-file-resizer#38]
When I create an image in blob type. I not contain uid, name, lastModified, lastModifiedDate

**Comment by OverStruck** [comment]
This is because the JavaScript [Blob ](https://developer.mozilla.org/en-US/docs/Web/API/Blob/Blob) object doesn't support the name attribute. If you are trying to use the Blob as a [File ](https://developer.mozilla.org/en-US/docs/Web/API/File) I've added a pull request to get a File object which does have a name attribute.
